### ISSUE TITLE
TypeError, possibly due to python2 / python3 language differences

### ISSUE THREAD

**Issue by simontindemans** [rmcgibbo/quadprog#6]
First of all, thank you for making this useful module available to the community. 

Today, I encountered an issue when running code on a CodeOcean compute capsule (essentially a docker container). The code runs fine locally, but on CodeOcean, my call to `solve_qp(...)` failed with 
`TypeError: 'float' object cannot be interpreted as an integer`

Since I was only supplying `solve_qp(...)` with `numpy` arrays and `meq=1`, the parameters are unlikely to be the problem. I looked further into the code and saw that line 91 of `quadprog.pyx` reads 
`cdef double[::1] work = np.zeros(2*n1+min(n1, m1)*(min(n1, m1)+5)/2 + 2*m1 +1)`
This appears to be Python 2 code, which assumes `x/2` returns an `int`. It may be the case that the default cython version in the docker container interprets the code as Python 3, thus leading to the error. 

I was able to solve the issue in my case by installing cython using conda, instead of having it installed as a dependency of quadprog - although I am not exactly sure *why* this would resolve it.

To avoid this issue cropping up elsewhere, it may be useful to replace `/` by `//` in the relevant line, or to explicitly specify `language_level=2` for cython.

**Comment by rmcgibbo** [comment]
> To avoid this issue cropping up elsewhere, it may be useful to replace / by // in the relevant line.

This sounds good to me. Would you like to submit  a pull request?

**Comment by simontindemans** [comment]
Ok, I have submitted one.

**Comment by rmcgibbo** [comment]
Great. Merged.
